version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "3001:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped 